language: java
sudo: false
install: true
notifications:
  slack: gruelbox:KxlNRVRsbXFQkO94YtHSdAmS
jdk: oraclejdk8
jobs:
  include:
    - if: (repo = gruelbox/XChange) AND (branch = orko OR tag IS present) AND (NOT type = pull_request)
      name: "Test and Deploy"
      script:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
        - mvn clean deploy --settings etc/settings.xml -B -U -Prelease
    - if: (NOT repo = gruelbox/XChange) OR (NOT branch = orko AND NOT tag IS present) OR (type = pull_request)
      name: "Test"
      script:
        - mvn clean test -B -U
cache:
  directories:
    - "$HOME/.m2/repository"
